apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: locust-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Prasnakumrn/my-argocd-locust-repo.git'
    targetRevision: HEAD
    path: locust
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
